apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: mrd83wcac-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/mrd83wcac-java-quarkus-gitops